# **************************************
# * Parameters for metprofile pipeline *
# **************************************

list_files: "/export/home/hramay/projects/Arrieta/PC1000/antibiotic_babies/analysis/metqc/list_files.txt"

# Path to sequences
path: "/export/home/hramay/projects/Arrieta/PC1000/antibiotic_babies/analysis/metqc/output/bmtagger/"


output_dir: "test"

# Nthreads metaphlan can use
threads: 4

# Are reads paired?
paired: TRUE

# If paired-end reads, suffix for forward reads
for: "_bmtagged_1.fastq"
# If paired-end reads, suffix for reverse reads
rev: "_bmtagged_2.fastq"

# If unpaired reads, suffix for reads
suff: "_bmt_merged_ELC_trimmed_filtered.fastq"
